---
- hosts: all
  become: yes
  tasks:
# OV moved to the beginning:
    - name: Update all yum packages
      yum: name=* state=latest
#    - name: disable all repos by default
#      shell: subscription-manager repos --disable="*"      
#    - name: Enable the requisite rhel7 repos
#      shell: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-optional-rpms" --enable="rhel-7-server-ose-3.0-rpms"
#    - name: Import keys
#      rpm_key: state=present key=/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta
#    - name: Remove Network Manager
#      yum: name=NetworkManager state=absent
    - name: Install pre requisites
      package: name={{ item }} state=present
#      dnf: name={{ item }} state=present
      with_items:
          - wget
          - git
          - unzip
          - libselinux-python
          - net-tools
          - bind-utils
          - iptables
          - iptables-services
          - bridge-utils
          - tmux
          - pyOpenSSL
          - python-dbus
          - NetworkManager
# OV added: (as found in oveits/installcentos/2_install-openshift-prerequisites.sh)
          #- wget
          #- git
          #- zile  # OV: not available
          - nano
          - net-tools
          - docker-1.13.1
          #- bind-utils
          - bash-completion
          - kexec-tools
          - sos
          - psacct
          - openssl-devel
          # needed for htpasswd:
          - httpd-tools
          # needed for htpasswd for hawkular metrics:
          - python-passlib-1.6.5-2.el7.noarch
          #- NetworkManager
          - python-cryptography
          #- python2-pip  # OV: not available
          - python-devel
          - python-passlib
          - java-1.8.0-openjdk-headless
          - "@Development Tools"
          - epel-release

    - name: Disable the EPEL repository globally so that is not accidentally used during later steps of the installation
      shell: 'sed -i -e "s/^enabled=1/enabled=0/" /etc/yum.repos.d/epel.repo'

# OV added:
    - name: Enable and Start NetworkManager
      service: name=NetworkManager state=started enabled=yes
    - name: Enable and Restart docker
      service: name=docker state=restarted enabled=yes

#    - name: Enable insecure registry... since we like insecure things
#      lineinfile: dest=/etc/sysconfig/docker state=present line='OPTIONS=--insecure-registry 172.30.0.0/16' regexp="^#?OPTIONS" 

