---
- hosts: all
  become: yes
  tasks:
#    - name: disable all repos by default
#      shell: subscription-manager repos --disable="*"      
#    - name: Enable the requisite rhel7 repos
#      shell: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-optional-rpms" --enable="rhel-7-server-ose-3.0-rpms"
#    - name: Import keys
#      rpm_key: state=present key=/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta
#    - name: Remove Network Manager
#      yum: name=NetworkManager state=absent
    - name: Install pre requisites
      yum: name={{ item }} state=present
#      dnf: name={{ item }} state=present
      with_items:
          - wget
          - git
          - unzip
          - libselinux-python
          - net-tools
          - bind-utils
          - iptables
          - iptables-services
          - bridge-utils
          - tmux
          - pyOpenSSL
          - python-dbus
          - NetworkManager
# OV added:
    - name: Enable NetworkManager (will automatically start on reboot)
      shell: systemctl enable NetworkManager
    - name: Enable and start NetworkManager
      shell: systemctl start NetworkManager
    - name: Update all yum packages
      yum: name=* state=latest
    - name: Install Docker
      yum: name=docker state=present
#      dnf: name=docker state=present
    - name: Enable insecure registry... since we like insecure things
      lineinfile: dest=/etc/sysconfig/docker state=present line='OPTIONS=--insecure-registry 172.30.0.0/16' regexp="^#?OPTIONS" 
    - name: Start docker
      service: name=docker state=started enabled=yes

